// Code generated by entc, DO NOT EDIT.

package manufacturer

const (
	// Label holds the string label denoting the manufacturer type in the database.
	Label = "manufacturer"
	// FieldID holds the string denoting the id field in the database.
	FieldID   = "id" // FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the manufacturer in the database.
	Table = "manufacturers"
)

// Columns holds all SQL columns for manufacturer fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
)
