// Code generated by entc, DO NOT EDIT.

package model

const (
	// Label holds the string label denoting the model type in the database.
	Label = "model"
	// FieldID holds the string denoting the id field in the database.
	FieldID   = "id" // FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"

	// Table holds the table name of the model in the database.
	Table = "models"
)

// Columns holds all SQL columns for model fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// DefaultName holds the default value on creation for the name field.
	DefaultName string
)
