// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/ekrtf/MotorHappy/ent/manufacturer"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// ManufacturerCreate is the builder for creating a Manufacturer entity.
type ManufacturerCreate struct {
	config
	mutation *ManufacturerMutation
	hooks    []Hook
}

// SetName sets the name field.
func (mc *ManufacturerCreate) SetName(s string) *ManufacturerCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetNillableName sets the name field if the given value is not nil.
func (mc *ManufacturerCreate) SetNillableName(s *string) *ManufacturerCreate {
	if s != nil {
		mc.SetName(*s)
	}
	return mc
}

// Save creates the Manufacturer in the database.
func (mc *ManufacturerCreate) Save(ctx context.Context) (*Manufacturer, error) {
	if _, ok := mc.mutation.Name(); !ok {
		v := manufacturer.DefaultName
		mc.mutation.SetName(v)
	}
	var (
		err  error
		node *Manufacturer
	)
	if len(mc.hooks) == 0 {
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ManufacturerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *ManufacturerCreate) SaveX(ctx context.Context) *Manufacturer {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (mc *ManufacturerCreate) sqlSave(ctx context.Context) (*Manufacturer, error) {
	var (
		m     = &Manufacturer{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: manufacturer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: manufacturer.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: manufacturer.FieldName,
		})
		m.Name = value
	}
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	m.ID = int(id)
	return m, nil
}
