// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Manufacturer is the predicate function for manufacturer builders.
type Manufacturer func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)
